obj:
  _target_: conformalbo.mobo_acquisitions.qConformalNoisyExpectedHypervolumeImprovement
  eta: 1e-3
  alpha: 0.
  prune_baseline: true
  sampler:
    _target_: botorch.sampling.samplers.IIDNormalSampler
    num_samples: 1
    batch_range: [0, -3]
params:
  - ref_point
  - X_baseline