obj:
  _target_: conformalbo.acquisitions.qConformalNoisyExpectedImprovement
  prune_baseline: true
  sampler:
    _target_: botorch.sampling.samplers.IIDNormalSampler
    num_samples: 1
    batch_range: [0, -3]
params:
  - X_baseline